# A Machine Learning Approach to Equity Premium Prediction
By Shane Johnson, Catherine Markley, Yuanhao Niu, Nick Rocco (Fall 2018 Data Science Project)

We try to use machine learning methods to predict equity premium based on predictors from the seminal paper of Goyal and Welch (2008) updates until 2013. Our algorithms improves the prediction of equity premium

## Data Cleaning

In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv("raw_predictors_until2013.csv")

Generate the predictors based on the raw data, as in Welch and Goyal (2008)

In [7]:
# equity premium, i.e., the total rate of return on the stock market minus the prevailing short-term interest rate.
df['premium'] = df['CRSP_SPvw'] - df['Rfree']

# Dividend Price Ratio (d/p) is the difference between the log of dividends and the log of prices. 
df['d/p'] = np.log(df['D12']) - np.log(df['Index'])

# Dividend Yield (d/y) is the difference between the log of dividends and the log of lagged prices.
df['d/y'] = np.log(df['D12'])- np.log(df['Index'].shift(1))

# Earnings Price Ratio (e/p) is the difference between the log of earnings and the log of prices.
df['e/p'] = np.log(df['E12']) - np.log(df['Index'])

# Dividend Payout Ratio (d/e) is the difference between the log of dividends and the log of earnings.
df['d/e'] = np.log(df['D12']) - np.log(df['E12'])

# Term Spread (tms) is the difference between the long term yield on government bonds and the T-bill.
df['tms'] = df['lty'] - df['tbl']

# Default Yield Spread (dfy): is the difference between BAA- and AAA- rated cor- porate bond yields.
df['dfy'] = df['BAA'] - df['AAA']

# Default Return Spread (dfr): is the difference between the return on long-term corporate bonds and returns on the long-term government bonds.
df['dfr'] = df['corpr'] - df['ltr']

In [8]:
# drop the first observation for 1926/12
df = df[1:]

We generate indicators for bull market. Machine learning methods are also used to predict the dicretion of market movements. 

In [9]:
sLength = len(df['yyyymm'])
# add the bullMarket column with random ints (to be replaced in next cell)
df['bull'] = pd.Series(np.random.randn(sLength), index=df.index)
# Create bullMarkert for ret
bull = []
for d in df['CRSP_SPvw']:
    if d > 0:
        bull.append(1)
    else:
        bull.append(0)
df['bull'] = bull

In [10]:
# drop the redundent variables
df = df.drop(columns=['Index','D12', 'E12', 'AAA', 'BAA', 'CRSP_SPvwx', 'corpr','Rfree', 'CRSP_SPvw'])

In [11]:
df.dtypes

yyyymm       int64
Month        int64
b/m        float64
tbl        float64
lty        float64
ntis       float64
infl       float64
ltr        float64
svar       float64
csp        float64
premium    float64
d/p        float64
d/y        float64
e/p        float64
d/e        float64
tms        float64
dfy        float64
dfr        float64
bull         int64
dtype: object

In [12]:
# impute the missing observations from 'csp'
def calc_average(data):
    sum = 0
    count = 0
    for i in data:
        if (i):
            sum += float(i)
            count += 1
    average = sum/count
    return average

In [13]:
temp = df['csp'][124:911]
avg = calc_average(temp)

In [14]:
df['csp'][0:124] = avg
df['csp'][912:]  = avg

/afs/crc.nd.edu/user/p/pbui/pub/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/afs/crc.nd.edu/user/p/pbui/pub/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [15]:
# reorganize the dataframe
df = df[['yyyymm','Month','bull','premium','d/p','d/y','e/p','d/e','svar',
          'csp','b/m','ntis','tbl','lty','ltr','tms','dfy','dfr','infl']]
df

yyyymm  Month  bull   premium       d/p       d/y       e/p       d/e  \
1     192701      1     0 -0.005602 -2.942374 -2.963349 -2.374773 -0.567601   
2     192702      2     1  0.042780 -2.979535 -2.932946 -2.430353 -0.549182   
3     192703      3     1  0.004657 -2.976535 -2.970053 -2.445079 -0.531456   
4     192704      4     1  0.010196 -2.984225 -2.967143 -2.471309 -0.512916   
5     192705      5     1  0.059578 -3.025963 -2.975058 -2.531446 -0.494518   
6     192706      6     0 -0.022928 -3.007309 -3.016743 -2.531330 -0.475979   
7     192707      7     1  0.081983 -3.061144 -2.998173 -2.603707 -0.457437   
8     192708      8     1  0.031070 -3.095764 -3.052225 -2.656742 -0.439023   
9     192709      9     1  0.050783 -3.129097 -3.086791 -2.707759 -0.421338   
10    192710     10     0 -0.049371 -3.065650 -3.120203 -2.662875 -0.402774   
11    192711     11     1  0.068013 -3.122543 -3.056966 -2.738218 -0.384325   
12    192712     12     1  0.016653 -3.132667 -3.113804 -2.766942 -0.365725   
13    192801      1     0 -0.009940 -3.118894 -3.124003 -2.741324 -0.377570   
14    192802      2     0 -0.015324 -3.092631 -3.110432 -2.704291 -0.388340   
15    192803      3     1  0.103027 -3.186980 -3.084114 -2.788289 -0.398691   
16    192804      4     1  0.031708 -3.210431 -3.178535 -2.800832 -0.409599   
17    192805      5     1  0.009075 -3.214759 -3.202181 -2.795243 -0.419516   
18    192806      6     0 -0.037597 -3.165110 -3.206453 -2.735254 -0.429857   
19    192807      7     1  0.006684 -3.169302 -3.156873 -2.729377 -0.439924   
20    192808      8     1  0.066597 -3.232747 -3.161253 -2.783671 -0.449077   
21    192809      9     1  0.018601 -3.248318 -3.224642 -2.790435 -0.457882   
22    192810     10     1  0.009922 -3.254680 -3.240278 -2.787459 -0.467221   
23    192811     11     1  0.119425 -3.360085 -3.246823 -2.884377 -0.475709   
24    192812     12     1  0.002682 -3.355051 -3.352172 -2.870448 -0.484602   
25    192901      1     1  0.051590 -3.398869 -3.343355 -2.912289 -0.486581   
26    192902      2     0 -0.008532 -3.381464 -3.387308 -2.892954 -0.488509   
27    192903      3     1 -0.003679 -3.367688 -3.370035 -2.876601 -0.491087   
28    192904      4     1  0.015559 -3.372320 -3.356388 -2.879407 -0.492913   
29    192905      5     0 -0.045523 -3.317413 -3.361147 -2.822717 -0.494696   
30    192906      6     1  0.108294 -3.412851 -3.306363 -2.916414 -0.496437   
...      ...    ...   ...       ...       ...       ...       ...       ...   
1015  201107      7     0 -0.019861 -3.960564 -3.982272 -2.722610 -1.237953   
1016  201108      8     0 -0.054339 -3.890788 -3.949255 -2.652008 -1.238780   
1017  201109      9     0 -0.070246 -3.805139 -3.879606 -2.565551 -1.239588   
1018  201110     10     1  0.108997 -3.891111 -3.788804 -2.667972 -1.223139   
1019  201111     11     0 -0.002735 -3.869971 -3.875043 -2.663016 -1.206956   
1020  201112     12     1  0.009419 -3.862650 -3.854153 -2.671627 -1.191023   
1021  201201      1     1  0.045180 -3.893673 -3.851013 -2.708210 -1.185463   
1022  201202      2     1  0.043265 -3.921954 -3.882166 -2.741957 -1.179996   
1023  201203      3     1  0.032799 -3.941433 -3.910582 -2.766805 -1.174628   
1024  201204      4     0 -0.006101 -3.922193 -3.929719 -2.761616 -1.160577   
1025  201205      5     0 -0.059865 -3.845912 -3.910611 -2.699259 -1.146653   
1026  201206      6     1  0.041390 -3.873259 -3.834466 -2.740400 -1.132859   
1027  201207      7     1  0.014280 -3.870941 -3.858422 -2.758316 -1.112625   
1028  201208      8     1  0.022661 -3.875889 -3.856318 -2.783315 -1.092574   
1029  201209      9     1  0.025028 -3.885427 -3.861480 -2.812719 -1.072708   
1030  201210     10     0 -0.017920 -3.846946 -3.866934 -2.792693 -1.054253   
1031  201211     11     1  0.005251 -3.831632 -3.828789 -2.795497 -1.036135   
1032  201212     12     1  0.008450 -3.820842 -3.813798 -2.802502 -1.018340   
1033  201301      1     1  0.052303 -3.860852 -3.811654 

We recognize the correlation in time series. In order to take full advantage of the past data, we include the past 20 years' data in the prediction. Here we generate predictors for the past 20 years, i.e. 240 months

In [16]:
past = 241

num = len(df.columns)
for i in range(4,num):
    name = df.columns[i]
    for j in range(1,past):
        t = str(j)
        df[name+"-"+t] = df[name].shift(j)

In [17]:
# drop the first past 20 years predictors
df = df[past-1:]
df.dtypes

yyyymm        int64
Month         int64
bull          int64
premium     float64
d/p         float64
d/y         float64
e/p         float64
d/e         float64
svar        float64
csp         float64
b/m         float64
ntis        float64
tbl         float64
lty         float64
ltr         float64
tms         float64
dfy         float64
dfr         float64
infl        float64
d/p-1       float64
d/p-2       float64
d/p-3       float64
d/p-4       float64
d/p-5       float64
d/p-6       float64
d/p-7       float64
d/p-8       float64
d/p-9       float64
d/p-10      float64
d/p-11      float64
             ...   
infl-211    float64
infl-212    float64
infl-213    float64
infl-214    float64
infl-215    float64
infl-216    float64
infl-217    float64
infl-218    float64
infl-219    float64
infl-220    float64
infl-221    float64
infl-222    float64
infl-223    float64
infl-224    float64
infl-225    float64
infl-226    float64
infl-227    float64
infl-228    float64
infl-229    float64


In [18]:
# drop the contemporanous predictors
df = df.drop(columns=['d/p','d/y','e/p','d/e','svar',
          'csp','b/m','ntis','tbl','lty','ltr','tms','dfy','dfr','infl'])

In [19]:
# column number 3604: 'yyyymm','Month','bull','premium' + 15 indicator * 240 months 
len(df.columns)

3604

## Regression (Equity Premium Prediction)

In [20]:
# for regression purpose
ret = df.premium
x = df.iloc[:,4:]

In [21]:
# for classification purpose
bull = df.bull
norm_x = (x- x.mean())/x.std(ddof=0)

We will first start with the simplest linear regression model. 

In [22]:
# Here are 67 years of data prior to 2013 
# Spilt the data into 7 folds and cross-validate
# In each sample we have around 10 years of data

# Linear Regression Model (Benmark)

from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.cross_validation import KFold

kf = KFold(x.shape[0],n_folds=7, shuffle=True)

MSE = []
R2 =[]

for train_index, test_index in kf:
    x_train, x_test = x.iloc[train_index], x.iloc[test_index]
    ret_train, ret_test = ret.iloc[train_index], ret.iloc[test_index]
    norm_x_train, norm_x_test = norm_x.iloc[train_index], norm_x.iloc[test_index]
    bull_train, bull_test = bull.iloc[train_index], bull.iloc[test_index]

    regr = linear_model.LinearRegression()
    regr.fit(x_train, ret_train)

    ret_pred = regr.predict(x_test)
    MSE.append(mean_squared_error(ret_test, ret_pred))
    R2.append(r2_score(ret_test, ret_pred))
    print("MSE: ", mean_squared_error(ret_test, ret_pred),"R2: ", r2_score(ret_test, ret_pred))
    
print( "the main take way: Mean(MSE) is", sum(MSE)/len(MSE),"Mean(R2) is", sum(R2)/len(R2))

/afs/crc.nd.edu/user/p/pbui/pub/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


MSE:  0.004194245028071128 R2:  -1.556632826019181
MSE:  0.004565943575337042 R2:  -0.9230466915118158
MSE:  0.005500704565346248 R2:  -3.7465506166125886
MSE:  0.0044032715510826095 R2:  -0.9023144652430093
MSE:  0.0038721233990784303 R2:  -1.2779577473350936
MSE:  0.004830986969116138 R2:  -2.0367140504677597
MSE:  0.003809673861126243 R2:  -1.5873959767880659
the main take way: Mean(MSE) is 0.004453849849879691 Mean(R2) is -1.7186589105682162


In [23]:
# dimension reduction (maybe PCA??)

In [24]:
# Random Forrest # Davids paper: random forest regression with 100 regression trees as a the forecasting function gt.

#  https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor

from sklearn.ensemble import RandomForestRegressor

MSE = []
R2 =[]

for train_index, test_index in kf:
    x_train, x_test = x.iloc[train_index], x.iloc[test_index]
    ret_train, ret_test = ret.iloc[train_index], ret.iloc[test_index]
    
    regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=100)
    regr.fit(x_train, ret_train)
    
    ret_pred = regr.predict(x_test)
    MSE.append(mean_squared_error(ret_test, ret_pred))
    R2.append(r2_score(ret_test, ret_pred))
    print("MSE: ", mean_squared_error(ret_test, ret_pred),"R2: ", r2_score(ret_test, ret_pred))
    
print( "the main take way: Mean(MSE) is", sum(MSE)/len(MSE),"Mean(R2) is", sum(R2)/len(R2))

MSE:  0.0016250243121831934 R2:  0.009454509261842436
MSE:  0.0023678681584482666 R2:  0.002720696629723518
MSE:  0.0011615390376546084 R2:  -0.0022904829559835527
MSE:  0.0023820465790431377 R2:  -0.029098844263255375
MSE:  0.001768250886393165 R2:  -0.04025631178234801
MSE:  0.001679896950417191 R2:  -0.055967798150189374
MSE:  0.001469069740305436 R2:  0.0022597014213505684
the main take way: Mean(MSE) is 0.001779099380635 Mean(R2) is -0.016168361405551397


In [25]:
# Random Forrest (another implementation)
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=10)
regr.fit(x_train, ret_train)
cross_val_score(regr, x, ret, scoring='neg_mean_squared_error',cv=7)  

array([-0.00142889, -0.00107345, -0.00221469, -0.00181998, -0.00202831,
       -0.00211922, -0.00213222])

In [26]:
# Boosted

# https://scikit-learn.org/stable/modules/ensemble.html#adaboost

from sklearn.ensemble import GradientBoostingRegressor

MSE = []
R2 =[]

for train_index, test_index in kf:
    x_train, x_test = x.iloc[train_index], x.iloc[test_index]
    ret_train, ret_test = ret.iloc[train_index], ret.iloc[test_index]
    
    regr = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=0, loss='ls')
    regr.fit(x_train, ret_train)
    
    ret_pred = regr.predict(x_test)
    MSE.append(mean_squared_error(ret_test, ret_pred))
    R2.append(r2_score(ret_test, ret_pred))
    print("MSE: ", mean_squared_error(ret_test, ret_pred),"R2: ", r2_score(ret_test, ret_pred))
    
print( "the main take way: Mean(MSE) is", sum(MSE)/len(MSE),"Mean(R2) is", sum(R2)/len(R2))

MSE:  0.0017347783409533992 R2:  -0.0574468641352206
MSE:  0.002404711507821208 R2:  -0.012796683282405574
MSE:  0.0012120541588763216 R2:  -0.04587991353433529
MSE:  0.0023972928854834813 R2:  -0.03568559889478906
MSE:  0.0017786388652609266 R2:  -0.04636752635433261
MSE:  0.0017236361417497105 R2:  -0.08346185220677893
MSE:  0.0014146347390168064 R2:  0.039230032338080534
the main take way: Mean(MSE) is 0.0018093923770231217 Mean(R2) is -0.03462977229568308


In [27]:
# Neural Nets

## Classification (Bull Market Prediction)

In [32]:
# decision tree CART algorithm

from sklearn import tree
from sklearn.metrics import confusion_matrix
clf = tree.DecisionTreeClassifier()
clf = clf.fit(norm_x_train, bull_train)
predicted = clf.predict(norm_x_test)
# print (predicted)
c_matrix = confusion_matrix(predicted,bull_test)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: ??")

[[20 30]
 [21 43]]
precision:  0.589041095890411
recall:  0.671875
the main take way: ??


In [33]:
# naive Bayes 
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(norm_x_train,bull_train).predict(norm_x_test)

predicted= gnb.predict(norm_x_test)

c_matrix = confusion_matrix(predicted,bull_test)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: ???")

[[23 46]
 [18 27]]
precision:  0.3698630136986301
recall:  0.6
the main take way: ???


In [34]:
# Support Vector Classification

from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(norm_x_train, bull_train) 

predicted= clf.predict(norm_x_test)

c_matrix = confusion_matrix(predicted,bull_test)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: ??? ")

[[ 2 11]
 [39 62]]
precision:  0.8493150684931506
recall:  0.6138613861386139
the main take way: ??? 


In [38]:
#K-Neighbors Classification

from sklearn.neighbors import KNeighborsClassifier 
clf = KNeighborsClassifier(n_neighbors=40)
clf.fit(norm_x_train, bull_train) 

predicted= clf.predict(norm_x_test)

c_matrix = confusion_matrix(predicted,bull_test)
precision = c_matrix[1,1]/(c_matrix[1,1]+c_matrix[0,1])
recall= c_matrix[1,1]/(c_matrix[1,1]+c_matrix[1,0])

print(c_matrix)  

print("precision: ", precision)  
print("recall: ", recall)  

print( "the main take way: ??? ")

[[ 7  5]
 [34 68]]
precision:  0.9315068493150684
recall:  0.6666666666666666
the main take way: ??? 
